# Generated by Django 5.2.10 on 2026-03-06 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_product_options_alter_product_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise')),
                ('status', models.CharField(choices=[('INIT', 'INIT'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='INIT', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('download_limit', models.PositiveSmallIntegerField(default=5)),
                ('download_used', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('is_deleted_by_user', models.BooleanField(default=False, help_text='Hide from UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DevOpsVaultX Payment',
                'verbose_name_plural': 'DevOpsVaultX Payments',
                'db_table': 'devopsvaultx_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
