# Generated by Django 5.2.10 on 2026-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_amount_payment_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, help_text='Amount in paise', null=True),
        ),
    ]
