# Generated by Django 5.2.10 on 2026-02-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_session_id_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'DevOpsVaultX Payment', 'verbose_name_plural': 'DevOpsVaultX Payments'},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='devopsvaultx_payments',
        ),
    ]
