# Generated by Django 5.2.10 on 2026-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_customer_name_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
