# Generated by Django 5.2.10 on 2026-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_email_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='old_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
