# Generated by Django 5.2.10 on 2026-02-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_old_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_otp_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
