# Generated by Django 5.2.10 on 2026-02-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payment_email_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False, help_text='Hide from UI'),
        ),
    ]
