# Generated by Django 5.2.10 on 2026-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_is_active_payment_is_deleted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='download_limit',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='download_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
