# Generated by Django 5.2.10 on 2026-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_download_limit_payment_download_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
