# Generated by Django 5.2.10 on 2026-02-26 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_is_renewal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'DevOpsVaultX Payment', 'verbose_name_plural': 'DevOpsVaultX Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email_otp_verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email_updated',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='old_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
