version: 2
updates:
  # Python Dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker Dependencies (Dockerfile & docker-compose)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"