services:
  # =========================
  # Django Web Service
  # =========================
  devopsvaultx_web:
    image: sachinthokal/devopsvaultx:1.0.0
    container_name: devopsvaultx_app
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - devopsvaultx_db
    networks:
      - devopsvaultx_network
    command: >
      sh -c "
      sleep 5 &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn devopsvaultx.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "

  # =========================
  # PostgreSQL Database
  # =========================
  devopsvaultx_db:
    image: postgres:15
    container_name: devopsvaultx_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - devopsvaultx_network

  # =========================
  # Nginx Proxy Manager (SSL & Reverse Proxy)
  # =========================
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: devopsvaultx_npm
    restart: always
    ports:
      - '80:80'    # HTTP
      - '81:81'    # NPM Dashboard Login
      - '443:443'  # HTTPS (SSL)
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - static_volume:/app/staticfiles  # Static files NPM madhun serve karnyathi
      - media_volume:/app/media         # Media files NPM madhun serve karnyathi
    depends_on:
      - devopsvaultx_web
    networks:
      - devopsvaultx_network

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
  static_volume:
  media_volume:

# =========================
# Networks
# =========================
networks:
  devopsvaultx_network: