# Generated by Django 5.2.10 on 2026-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'DB Size Report',
                'verbose_name_plural': 'DB Size Reports',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatabaseSizeReport',
        ),
    ]
