# Generated by Django 5.2.10 on 2026-02-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_monitor', '0002_dbsize_delete_databasesizereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product Summary Report',
                'verbose_name_plural': 'Product Summary Reports',
                'managed': False,
            },
        ),
    ]
