# Generated by Django 5.2.10 on 2026-02-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_monitor', '0003_paymentsummary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbsize',
            table='devopsvaultx_db_size_report',
        ),
        migrations.AlterModelTable(
            name='paymentsummary',
            table='devopsvaultx_product_summary',
        ),
    ]
