# Generated by Django 5.2.10 on 2026-02-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_monitor', '0004_alter_dbsize_table_alter_paymentsummary_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsummary',
            options={'managed': False, 'verbose_name': 'DevOpsVaultX Product Summary Report', 'verbose_name_plural': 'DevOpsVaultX Product Summary Reports'},
        ),
    ]
