# Generated by Django 5.2.10 on 2026-02-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'DevOpsVaultX Contact Message', 'verbose_name_plural': 'DevOpsVaultX Contact Messages'},
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='devopsvaultx_contact_messages',
        ),
    ]
