# Generated by Django 5.2.10 on 2026-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('log_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DevOpsVaultX System Log',
                'verbose_name_plural': 'DevOpsVaultX System Logs',
                'db_table': 'devopsvaultx_systemlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
