# Generated by Django 5.2.10 on 2026-03-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemlog',
            table='devopsvaultx_systemlogs',
        ),
    ]
