# Generated by Django 5.2.10 on 2026-02-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('blog', 'Blog'), ('offer', 'Offer')], max_length=10)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('mark_new', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DevOpsVaultX Insights Post',
                'verbose_name_plural': 'DevOpsVaultX Insights Posts',
                'db_table': 'devopsvaultx_insights_posts',
                'ordering': ['-is_pinned', 'priority', '-created_at'],
            },
        ),
    ]
