# ==============================
# 1. Custom JSON Log Format
# ==============================
log_format json_analytics escape=json '{'
  '"time_local":"$time_local",'
  '"remote_addr":"$remote_addr",'
  '"request":"$request",'
  '"status": "$status",'
  '"body_bytes_sent":"$body_bytes_sent",'
  '"request_time":"$request_time",'
  '"http_referrer":"$http_referer",'
  '"http_user_agent":"$http_user_agent"'
'}';

# ==============================
# 2. HTTP → Redirect to HTTPS
# ==============================
server {
    listen 80;
    server_name devopsvaultx.com www.devopsvaultx.com;
    
    # Use custom JSON log
    access_log /var/log/nginx/access_file.log json_analytics;
    error_log  /var/log/nginx/error_file.log warn;
    
    return 301 https://devopsvaultx.com$request_uri;
}

# ==============================
# 3. Redirect WWW to Non-WWW
# ==============================
server {
    listen 443 ssl;
    server_name www.devopsvaultx.com;

    ssl_certificate /etc/letsencrypt/live/devopsvaultx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devopsvaultx.com/privkey.pem;

    access_log /var/log/nginx/access_file.log json_analytics;
    error_log  /var/log/nginx/error_file.log warn;

    return 301 https://devopsvaultx.com$request_uri;
}

# ==============================
# 4. Main HTTPS Server
# ==============================
server {
    listen 443 ssl;
    server_name devopsvaultx.com;

    # Pointing access log to use the JSON format
    access_log /var/log/nginx/access_file.log json_analytics;
    error_log  /var/log/nginx/error_file.log warn;

    ssl_certificate /etc/letsencrypt/live/devopsvaultx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devopsvaultx.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Static files
    location /static/ {
        alias /app/staticfiles/;
        access_log off; # Static files sathi logs band thevle tari chalel (storage vachel)
    }

    # Media files
    location /media/ {
        alias /app/media/;
        access_log off;
    }

    # Django App
    location / {
        proxy_pass http://devopsvaultx_web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        # Timeout settings (Standard for Gunicorn)
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
    }
}