# Generated by Django 5.2.10 on 2026-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultpost',
            options={'ordering': ['-is_pinned', 'priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='vaultpost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultpost',
            name='mark_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultpost',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
