# Generated by Django 5.2.10 on 2026-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vaultpost_options_vaultpost_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultpost',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
