# Generated by Django 5.2.10 on 2026-02-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_vaultpost_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultpost',
            options={'ordering': ['-is_pinned', 'priority', '-created_at'], 'verbose_name': 'Vault Post', 'verbose_name_plural': 'Vault Posts'},
        ),
        migrations.AlterModelTable(
            name='vaultpost',
            table='vault_posts',
        ),
    ]
