# Generated by Django 5.2.10 on 2026-02-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_vaultpost_options_alter_vaultpost_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultpost',
            options={'ordering': ['-is_pinned', 'priority', '-created_at'], 'verbose_name': 'DevOpsVaultX Vault Post', 'verbose_name_plural': 'DevOpsVaultX Vault Posts'},
        ),
        migrations.AlterModelTable(
            name='vaultpost',
            table='devopsvaultx_vault_posts',
        ),
    ]
