# Generated by Django 6.0.1 on 2026-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('notes', 'Notes'), ('courses', 'Courses'), ('templates', 'Templates'), ('tools', 'Tools')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
