# Generated by Django 5.2.10 on 2026-02-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'DevOpsVaultX Product', 'verbose_name_plural': 'DevOpsVaultX Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='devopsvaultx_products',
        ),
    ]
